### ISSUE TITLE
Map stats in one page

### ISSUE THREAD

**Issue by cyperdark** [MikiraSora/OsuLiveStatusPanel#3]
- star
- ar
- od
- cs
- hp
- bpm
Add this info to one page: http://localhost:10800/api/olsp/mapstats

**Comment by MikiraSora** [comment]
what's format for bpm ? there are only "max_bpm" and "min_bpm" here.

**Comment by MikiraSora** [comment]
[Done.](https://github.com/OsuSync/OsuDataDistributeRestful/commit/05b974c4f43f573546ef435f6f0a30df1e970b7f)
