### ISSUE TITLE
System.IO.DirectoryrJotFoundException: Could not find a part of the path 'F:\output'.

### ISSUE THREAD

**Issue by eiiot** [MikiraSora/OsuLiveStatusPanel#7]
![image](https://user-images.githubusercontent.com/39346975/99892377-2de20300-2c29-11eb-8489-b8d0bb629834.png)
I'm getting this when starting sync. The only thing that I have done recently is installing hawk drivers, and I don't think that should effect sync.

Edit: I plugged in my backup, and now it's working? Why did sync create the output folder on F: instead of C:

**Comment by MikiraSora** [comment]
please checkout and modify path in your PPConfigShow.json
